### ISSUE TITLE
Show Movies Grid on Master Screen

### ISSUE THREAD

**Issue by soygabimoreno** [Architect-Coders/Equipo5#11]
AS a User
GIVEN this end point: `https://api.themoviedb.org/3/`
WHEN I open the app
THEN I want to see a list of movies shown like this:
- RecyclerView with Grid Layout
- 3 items per file

**Comment by davthecodercom** [comment]
@soygabimoreno Hechale un vistazo a este issue, si esta hecho muevelo a close

**Comment by davthecodercom** [comment]
hecho y mergeado
