### ISSUE TITLE
DeepLinks through Navigation Graph

### ISSUE THREAD

**Issue by adrianlazaro8** [Architect-Coders/Equipo5#29]

**Comment by adrianlazaro8** [comment]
La dejo bloqueada hasta que en el movieDetail carguemos la info de la película a través del id de la misma.

**Comment by davthecodercom** [comment]
Muevo este Issue a **TO DO**, ya que este ticket se deblockea con el siguiente PR: https://github.com/Architect-Coders/Equipo5/pull/55
