### ISSUE TITLE
CIN-000: [SPIKE] Investigate about  how integtegrate SonarQube and advantages

### ISSUE THREAD

**Issue by davthecodercom** [Architect-Coders/Equipo5#3]
AS a developer team
GIVEN investigate about SonarQube
THEN improve the code of our project 
WHEN before merge pull request in to develop

Please investigate how to integrate [SonarQube](https://www.sonarqube.org/) and which advantages can we have as a team using this tool.
Please report the length of the integration and the advantages we will get if we use it for this project.
So we all can decide if it worth to use it in this specific case or not.

**Comment by DavidCruzUK** [comment]
@adrianlazaro8 Hechale un vistazo a este issue, si esta hecho muevelo a close

**Comment by davthecodercom** [comment]
@adrianlazaro8 no se si esta tarea sigue interesando, veamos si esta pendiente o lo cerramos y cerramos el PR
