### ISSUE TITLE
Update gitignore in development branch

### ISSUE THREAD

**Issue by soygabimoreno** [Architect-Coders/Equipo5#30]

**Comment by davthecodercom** [comment]
@soygabimoreno Hechale un vistazo a este bug, si esta mergeado muevelo a close. Gracias

**Comment by soygabimoreno** [comment]
Estoy capullo... lo había movido a mano a DONE en el tablero. Cuando lo único que tenía que hacer era cerrarlo... 1000 gracias!!!
