### ISSUE TITLE
Pass id value between Master and Detail Fragments

### ISSUE THREAD

**Issue by gabrielpozo** [Architect-Coders/Equipo5#35]
Using safe-args library from Navigation component, we will set the movie-id value on MasterScreen and this one will be retrieved on DetailFragment in order to get the movie detail specifications

**Comment by davthecodercom** [comment]
@adrianlazaro8 Este ticket lo voy a hacer con la vista detalle, me lo asigno a mi y hago la tarea junta

**Comment by soygabimoreno** [comment]
De cine, @DavidCruzUK

**Comment by adrianlazaro8** [comment]
Perfecto @DavidCruzUK , sin problema
