### ISSUE TITLE
[SPIKE] Investigate/RnD about Deferred

### ISSUE THREAD

**Issue by davthecodercom** [Architect-Coders/Equipo5#52]
As we mention in the previous meeting, we open this ticket in order to research about Deferred.
Some Helpful docs:
https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-deferred/
https://kotlinlang.org/docs/tutorials/coroutines/coroutines-basic-jvm.html

**Comment by soygabimoreno** [comment]
Un `Deferred` es un `Job`. Nos sirve para poder devolver como resultado de una función algo que va a ser obtenido en el futuro de manera asíncrona.

**Comment by davthecodercom** [comment]
@soygabimoreno como supongo esto ya esta claro la cierro
